services:
   kerjasama-api:
      container_name: kerjasama-api
      image: kerjasama-api
      build:
         context: ./api
         dockerfile: ./Dockerfile
      ports:
         - 1010:80
      volumes:
         - ./api:/var/www/html
      restart: always
      networks:
         - pps-network

   kerjasama-admin:
      container_name: kerjasama-admin
      image: kerjasama-admin
      build:
         context: ./admin
         dockerfile: ./Dockerfile
      ports:
         - "1011:80"
      environment:
         - NODE_ENV=production
      restart: always

   kerjasama-frontend:
      container_name: kerjasama-frontend
      image: kerjasama-frontend
      build:
         context: ./frontend
         dockerfile: ./Dockerfile
      ports:
         - "1012:80"
      environment:
         - NODE_ENV=production
      restart: always

networks:
   pps-network:
      external: true
      name: pps-network
